### ISSUE TITLE
Bug report: No notifications

### ISSUE THREAD

**Issue by yinghang** [nickzuber/meteorite#27]
<img width="1532" alt="screenshot 2018-11-10 21 28 31" src="https://user-images.githubusercontent.com/4490352/48308298-96248700-e52f-11e8-8d9c-10a57fd24742.png">

**Comment by yinghang** [comment]
Help! Why do i have no notifications??

**Comment by nickzuber** [comment]
It's saturday, i'd hope you aren't getting any updates!
