### ISSUE TITLE
More descriptive context name could be used

### ISSUE THREAD

**Issue by yinghang** [nickzuber/meteorite#28]
https://github.com/nickzuber/meteorite/blob/cd5f8b6485abdedeec7abc5488c55af113d3b74c/src/providers/Auth.js#L5

**Comment by yinghang** [comment]
Using `'foo'` makes this project sound like a joke

**Comment by nickzuber** [comment]
Oops that's not supposed to be there — it doesn't do anything. Will remove, thanks ying
