### ISSUE TITLE
Request - `Resolved` -> `Trash`

### ISSUE THREAD

**Issue by nickzuber** [nickzuber/meteorite#32]
Improve the name by making it more clear what that tab is

**Comment by zachdunn** [comment]
"Archived" might be better fit, since "Trash" implies it isn't valuable for historical context (analytics?) either.

**Comment by nickzuber** [comment]
Archived is the _perfect_ word here, thank you!!

**Comment by nickzuber** [comment]
Fixed in 268804c8e3dcbfc80ce4301316f13db4c250d79f
