### ISSUE TITLE
Request - Indicate Issue/PR status

### ISSUE THREAD

**Issue by ajwhite** [nickzuber/meteorite#37]
It would be awesome to see the status of the issue/PR notification.

I generally filter these out when looking through which notifications to read & respond to.

**Comment by nickzuber** [comment]
I'd also love this – last I checked, there was a weird bug with GitHub's notifications API that wouldn't properly update the reason for the notification when it was closed/merged. 

We can look into it again though

**Comment by nickzuber** [comment]
Closing this until GitHub fixes their REST api (will probably never happen)
