### ISSUE TITLE
Bug - Desktop Notifications

### ISSUE THREAD

**Issue by asantarissy** [nickzuber/meteorite#39]
**Browser**: Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)
**OS**: macOS Mojave Version 10.14.3

**Issue**:
I'm not receiving any notification on my desktop.
![screen shot 2019-02-28 at 12 42 07 pm](https://user-images.githubusercontent.com/522352/53563427-a69f5280-3b5c-11e9-95f7-06fb9764c6fb.png)

**Comment by nickzuber** [comment]
Hmm interesting, I wonder if you had originally declined notifications when they were first prompted at the browser level -— do you remember?

**Comment by asantarissy** [comment]
> Hmm interesting, I wonder if you had originally declined notifications when they were first prompted at the browser level -— do you remember?

No not really, It's allowed from the first visit and I didn't change it, I did run it locally but I don't think this is the issue. Could you please check if my token is stored or not?

Thanks @nickzuber

**Comment by asantarissy** [comment]
One more thing @nickzuber, I'd love to be part of Meteorite team and maintain this awesome project, let me know if that is possible.

Cheers!
