### ISSUE TITLE
Request - Adjust syncer based on use

### ISSUE THREAD

**Issue by nickzuber** [nickzuber/meteorite#6]
Something like an inverted percentage backoff as the hourly limit is approaching.

I might not be using it a lot, but someone with a ton of notifications and subscribed to a lot of different repos (ahem, attius) might.

**Comment by zachdunn** [comment]
If you move this responsibility to a service worker, you could be more consistent about polling frequency and cache between reloads. Paired w/ tab visibility API, this also addresses issue where multiple tabs open would increase consumption.

**Comment by nickzuber** [comment]
That's a good point with the multiple tabs — fortunately GitHub's notifications API is optimized for polling and we can pass an `If-Modified-Since` header to our requests that won't affect the rate limit.

This means the only time we'll be using up our rate limit is when the user is actually getting new notifications. So we can technically make 1 request a second and still be okay, but that'd be really rude to GitHub's servers.

I think a good way to handle this would be to see if a user is actually approaching the limit and have some kind of backoff strategy if they're getting there quickly.

For reference, I get a decent amount of notifications a day and I've never dropped below 4950/5000 requests for an hour, so I don't think this is a particularly urgent problem but definitely one to keep thinking about

**Comment by nickzuber** [comment]
Closed due to this not being something we need to worry about atm
