### ISSUE TITLE
Question - Unable to connect Githhub notifications to Meteorite desktop app

### ISSUE THREAD

**Issue by marcmansueto** [nickzuber/meteorite#60]
Hello, Nick. I am having trouble connecting my github notifications to Meteorite. I followed directions from the How to Use page, but still no connections. Any tips?

Also, apologies in advance. I'm a novice with programming.

**Comment by nickzuber** [comment]
Hey! Sorry for the delay – what errors if any are you running into?

**Comment by marcmansueto** [comment]
Nick, my apologies. Got the website working, but now can't find the app to work from my desktop. I had it before and it disappeared. Is there anyway I can recover it? Thank you.
