### ISSUE TITLE
Bug - Heroku token provider offline

### ISSUE THREAD

**Issue by keisans** [nickzuber/meteorite#76]
It looks like the gatekeeper instance for production got hit when heroku took down the free tier.

![Screenshot 2023-01-20 at 9 25 25 AM](https://user-images.githubusercontent.com/627906/213722561-5d655639-e01e-4f85-a93c-1cda72bed039.png)

I'm able to reproduce this issue consistently in production when trying to log in with my github account.

I think this functionality should be relatively easy to transition to a netlify, vercel, or cloudflare cloud function. Some prior art from a quick google search:

- https://github.com/gr2m/cloudflare-worker-github-oauth-login
- https://github.com/cadbox1/github-oktokit-oauth-netlify

**Comment by nickzuber** [comment]
@keisans Thanks for bumping this Ryan! I have a fix already, just need to deploy it 👍

**Comment by nickzuber** [comment]
@keisans So sorry for the wait — I haven't had to publish a release in like 2 years so the tools I was using were all deprecated and I had to upgrade things lol.

**Good news:** Logging in should work again!
**Good-er news:** If you enjoy Meteorite, I have a new project in the works that's like Meteorite but 10x better... 👀 stay tuned...

**Comment by nickzuber** [comment]
Closing because this should be fixed — if not please reopen!
